### Find developers by search query (?q=)
GET http://localhost:3000/developers


### Find a developer by id
GET http://localhost:3000/developers/3


### Create a developer
POST http://localhost:3000/developers
Content-Type: application/json

{
  "title": "Konami"
}


### Update a developer
PATCH http://localhost:3000/developers/1
Content-Type: application/json

{
  "title": "Capcom"
}


### Delete a developer
DELETE http://localhost:3000/developers/1
Content-Type: application/json


### Add developers to a game
PATCH http://localhost:3000/developers/addtogame
Content-Type: application/json

{
  "gameId": 2,
  "metaName": "developers",
  "metaIds": [3, 2]
}

### Remove developers from a game
PATCH http://localhost:3000/developers/removefromgame
Content-Type: application/json

{
  "gameId": 2,
  "metaName": "developers",
  "metaIds": [3, 2]
}