### Find users by search query
GET http://localhost:3000/users?q=m


### Get signed in user (current user)
GET http://localhost:3000/users/whoami


### Find a user by id
GET http://localhost:3000/users/1


### Signup
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "nickname": "Simon",
  "password": "12345678"
}


### Signin
POST http://localhost:3000/users/signin
Content-Type: application/json

{
  "nickname": "Simon",
  "password": "12345678"
}


### Signout
GET http://localhost:3000/users/signout


### Set admin
POST http://localhost:3000/users/setadmin
Content-Type: application/json

{
  "userId": 1,
  "adminKey": "admin_key",
  "value": true
}


### Update a user
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
  "nickname": "Samus"
}


### Delete a user
DELETE http://localhost:3000/users/1
Content-Type: application/json