### Find games by search query
GET http://localhost:3000/games?q=m


### Find a game by id
GET http://localhost:3000/games/2


### Create a game
POST http://localhost:3000/games
Content-Type: application/json

{
  "title": "Megaman",
  "releaseDate": "2019-07-04T13:33:03.000Z"
}


### Update a game
PATCH http://localhost:3000/games/1
Content-Type: application/json

{
  "title": "Mario"
}


### Delete a game
DELETE http://localhost:3000/games/1
Content-Type: application/json