### Find all gamelists
GET http://localhost:3000/gamelists


### Find gamelists by search query
GET http://localhost:3000/gamelists?q=s


### Find a gamelist by id
GET http://localhost:3000/gamelists/1


### Create a gamelist
POST http://localhost:3000/gamelists
Content-Type: application/json

{
  "title": "List #1"
}


### Update a gamelist
PATCH http://localhost:3000/gamelists/1
Content-Type: application/json

{
  "title": "My list"
}


### Delete a gamelist
DELETE http://localhost:3000/gamelists/1
Content-Type: application/json


### Add games to a gamelist
PATCH http://localhost:3000/gamelists/addgames
Content-Type: application/json

{
  "gamelistId": 1,
  "gameIds": [2, 3]
}


### Remove games from a gamelist
PATCH http://localhost:3000/gamelists/removegames
Content-Type: application/json

{
  "gamelistId": 1,
  "gameIds": [2, 3]
}