### Find all games
GET http://localhost:3000/games


### Search games
GET http://localhost:3000/games/search?title=m&years[]=2019&developers[]=2&page=1


### Find games by the first letter of alphabet
GET http://localhost:3000/games/alphabet?q=m


### Find games by search query
GET http://localhost:3000/games?q=m


### Find a game by id
GET http://localhost:3000/games/6


### Create a game
POST http://localhost:3000/games
Content-Type: application/json

{
  "title": "Megaman",
  "releaseDate": "2019-07-04T13:33:03.000Z"
}


### Update a game
PATCH http://localhost:3000/games/1
Content-Type: application/json

{
  "title": "Mario"
}


### Delete a game
DELETE http://localhost:3000/games/5
Content-Type: application/json


### Create a game with image
POST http://localhost:3000/games
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="image"; filename="blue-vector-pattern.jpg"
Content-Type: image/jpeg

< ./img/blue-vector-pattern.jpg
--MfnBoundry
Content-Disposition: form-data; name="title"

Battletoads
--MfnBoundry
Content-Disposition: form-data; name="releaseDate"

2019-07-04T13:33:03.000Z
--MfnBoundry--


### Upload image with validator exception
PATCH http://localhost:3000/games/6
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="image"; filename="blue-vector-pattern.jpg"
Content-Type: image/jpeg

< ./img/blue-vector-pattern.jpg
--MfnBoundry--